# Generated by Django 3.2.7 on 2021-10-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('bloodgroup', models.CharField(max_length=15)),
                ('phno', models.CharField(max_length=15)),
            ],
        ),
    ]
